#!/usr/bin/env bash
# setup.sh — install Moltis + Lersi MCP server + Telegram, configured via .env
set -euo pipefail

# ── Helpers ─────────────────────────────────────────────────────────────────

log()  { printf '\033[1;32m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33mwarn: %s\033[0m\n' "$*"; }
die()  { printf '\033[1;31merror: %s\033[0m\n' "$*" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Load .env ────────────────────────────────────────────────────────────────

ENV_FILE="${SCRIPT_DIR}/.env"

if [ ! -f "$ENV_FILE" ]; then
  cat > "$ENV_FILE" <<'EOF'
# Lersi + Moltis setup — fill in all values before running setup.sh

# ── Xiaomi MiMo API ──────────────────────────────────────────────────────────
# Get your key from: https://platform.xiaomimimo.com/#/docs/quick-start/first-api-call
MIMO_API_KEY=

# MiMo model to use (mimo-v2-pro or mimo-v2-flash)
MIMO_MODEL=mimo-v2-pro

# ── Telegram ─────────────────────────────────────────────────────────────────
# Create a bot with @BotFather on Telegram and paste the token here
TELEGRAM_BOT_TOKEN=

# Your Telegram user ID (message @userinfobot to find it)
# Can be numeric ID or username, e.g.: 123456789 or alice_username
TELEGRAM_ALLOWED_USER=

# DM policy: "allowlist" (only TELEGRAM_ALLOWED_USER), "open" (anyone), "disabled"
TELEGRAM_DM_POLICY=allowlist

# Group policy: "open" (any group), "allowlist", "disabled"
TELEGRAM_GROUP_POLICY=open

# ── Moltis ───────────────────────────────────────────────────────────────────
# Port for the Moltis web UI (default: 13131)
MOLTIS_PORT=13131

# Bot display name in the web UI
MOLTIS_BOT_NAME=lersi-bot

# ── Lersi DB (optional) ───────────────────────────────────────────────────────
# Leave blank to use the default platform data dir (~/.local/share/lersi/lersi.db)
LERSI_DB_PATH=
EOF
  warn ".env not found — created a template at .env"
  warn "Fill in your values then run this script again."
  exit 1
fi

# Source .env (skip blank lines and comments)
set -a
# shellcheck disable=SC1090
while IFS= read -r line; do
  [[ "$line" =~ ^[[:space:]]*# ]] && continue
  [[ -z "${line// }" ]] && continue
  export "${line?}"
done < "$ENV_FILE"
set +a

# ── Validate required vars ───────────────────────────────────────────────────

check_var() {
  local var="$1" label="$2"
  local val="${!var:-}"
  if [ -z "$val" ]; then
    die "$label is not set. Edit .env and set $var."
  fi
}

check_var MIMO_API_KEY "Xiaomi MiMo API key"
check_var TELEGRAM_BOT_TOKEN  "Telegram bot token"
check_var TELEGRAM_ALLOWED_USER "Telegram allowed user"

MIMO_MODEL="${MIMO_MODEL:-mimo-v2-pro}"
MOLTIS_PORT="${MOLTIS_PORT:-13131}"
MOLTIS_BOT_NAME="${MOLTIS_BOT_NAME:-lersi-bot}"
TELEGRAM_DM_POLICY="${TELEGRAM_DM_POLICY:-allowlist}"
TELEGRAM_GROUP_POLICY="${TELEGRAM_GROUP_POLICY:-open}"

# ── 1. Install Moltis ────────────────────────────────────────────────────────

log "Installing Moltis..."

if command -v moltis &>/dev/null; then
  log "Moltis already installed: $(moltis --version 2>/dev/null || echo '?')"
else
  curl -fsSL https://www.moltis.org/install.sh | sh
  # Add to PATH for the rest of this script if needed
  export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
  command -v moltis &>/dev/null || die "Moltis install failed — binary not found in PATH"
  log "Moltis installed: $(moltis --version)"
fi

# ── 2. Build + install Lersi ─────────────────────────────────────────────────

log "Building Lersi MCP server..."

if ! command -v cargo &>/dev/null; then
  die "Rust/Cargo not found. Install from https://rustup.rs then re-run this script."
fi

(cd "$SCRIPT_DIR" && cargo build --release --quiet)
LERSI_BIN="$SCRIPT_DIR/target/release/lersi"
[ -x "$LERSI_BIN" ] || die "Lersi build failed — binary not found at $LERSI_BIN"
log "Lersi built: $LERSI_BIN"

# ── 3. Write moltis.toml ─────────────────────────────────────────────────────

MOLTIS_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/moltis"
mkdir -p "$MOLTIS_CONFIG_DIR"
CONFIG_FILE="$MOLTIS_CONFIG_DIR/moltis.toml"

log "Writing $CONFIG_FILE..."

# Build LERSI_DB env block only if the var is set
LERSI_ENV_BLOCK=""
if [ -n "${LERSI_DB_PATH:-}" ]; then
  LERSI_ENV_BLOCK="
[mcp.servers.lersi.env]
LERSI_DB_PATH = \"${LERSI_DB_PATH}\""
fi

cat > "$CONFIG_FILE" <<EOF
# moltis.toml — generated by setup.sh
# Edit directly or re-run setup.sh to regenerate from .env

[identity]
name = "${MOLTIS_BOT_NAME}"

# ── Provider: Xiaomi MiMo (OpenAI-compatible) ────────────────────────────────

[providers]
offered = ["custom-mimo"]

[providers.custom-mimo]
enabled  = true
api_key  = "${MIMO_API_KEY}"
base_url = "https://api.xiaomimimo.com/v1"
models   = ["${MIMO_MODEL}"]

[chat]
priority_models = ["${MIMO_MODEL}"]

# ── MCP: Lersi spaced-repetition server ─────────────────────────────────────

[mcp]
request_timeout_secs = 30

[mcp.servers.lersi]
command = "${LERSI_BIN}"
args    = []
${LERSI_ENV_BLOCK}

# ── Channel: Telegram ────────────────────────────────────────────────────────

[channels]
offered = ["telegram"]

[channels.telegram.my-bot]
token          = "${TELEGRAM_BOT_TOKEN}"
dm_policy      = "${TELEGRAM_DM_POLICY}"
group_policy   = "${TELEGRAM_GROUP_POLICY}"
allowlist      = ["${TELEGRAM_ALLOWED_USER}"]
model          = "${MIMO_MODEL}"
model_provider = "custom-mimo"
stream_mode    = "edit_in_place"
reply_to_message = true

# ── Server ────────────────────────────────────────────────────────────────────

[server]
port = ${MOLTIS_PORT}
EOF

log "Config written to $CONFIG_FILE"

# ── 4. Smoke-test the Lersi binary ───────────────────────────────────────────

log "Smoke-testing Lersi..."
response=$(echo '{"jsonrpc":"2.0","method":"initialize","id":1}' | "$LERSI_BIN" 2>/dev/null | head -1)
if echo "$response" | grep -q '"name":"lersi"'; then
  log "Lersi responds correctly to MCP initialize."
else
  warn "Lersi smoke test returned unexpected output: $response"
fi

# ── Done ─────────────────────────────────────────────────────────────────────

cat <<EOF

$(printf '\033[1;32m')Setup complete!$(printf '\033[0m')

  Config:  $CONFIG_FILE
  Lersi:   $LERSI_BIN

To start Moltis:

  moltis

Then open:  http://localhost:${MOLTIS_PORT}

Your Telegram bot (@${MOLTIS_BOT_NAME}) will be live once Moltis starts.
The Lersi MCP tools (learn__start_topic, learn__next_concept, etc.)
are available to the agent automatically via the MCP connection.

To run as a background service:

  # systemd (Linux)
  moltis service install && systemctl --user start moltis

  # launchd (macOS)
  moltis service install && launchctl load ~/Library/LaunchAgents/com.moltis.agent.plist

EOF
